image: $DOCKER_IMAGE

before_script:
# sudo is necessary for setup-enviroment.sh script
  - apt-get --allow-releaseinfo-change update && apt-get install -y --no-install-recommends git build-essential sudo
  - ./.github/scripts/setup-environment.sh
  - git submodule update --init --recursive

test:
  script:
    - ./.github/scripts/test.sh
  artifacts:
    paths:
      - out/
