name: build-and-test-design

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
         ./.github/scripts/setup-environment.sh
         make testall
